### PR TITLE
Changes discussed now implemented

### PR DESCRIPTION
**Pull request by js21**
. Created builder methods for number_of_het_snps and total_number_of_snps
. Removed the calculate_percentage method and the percentage attributes
. Added attributes for all the temp vcfs and cv files
. Simplified the het snps calculation in TrackQC_Fasta

### CODE REVIEW

**Comment by js21** [comment]
Stats_and_graphs and Het_Snps could share the same functionality when getting the reference_size.
A sub-routine get_reference_size could be put in place that returns 3 values.
Het_Snps only needs the first value returned.
Stats_And_graphs needs all.

At the moment I left the code as it was initially (with duplication)

**Comment by bewt85** [comment]
Morning @js21, is this now ready to be reviewed / merged?

**Comment by js21** [comment]
Good morning @bt5, it is indeed.

Sorry for not replying earlier.

J

On 20/05/2015 09:44, Ben Taylor wrote:
>
> Morning @js21 <https://github.com/js21>, is this now ready to be 
> reviewed / merged?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sanger-pathogens/vr-codebase/pull/328#issuecomment-103812654>.
>

-- 
Jorge Soares - Senior Bioinformatician
Pathogen Informatics
Wellcome Trust Sanger Institute




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by bewt85** [comment]
@js21, thanks for your patience.  When this is merged, I suggest that you run perl tidy and stick in a PR with just those changes which I will merge before you deploy this to production.

Cheers, Ben

**Pull request merged**
