### PR TITLE
Farm5

### PR DESCRIPTION
**Pull request by seretol**

### CODE REVIEW

**Comment by seretol** [comment]
Merging farm5 into master

**Comment by puethe** [comment]
Is this the "digestible" pull request we were talking about? ;)
Don't see the release of master before the merge that we agreed on, where can I find that?

**Comment by seretol** [comment]
I supposed that's the exception, long lived branches….

Pushed tagged ﻿farm3_latest based on the latest commit of the current farm3 install.

Best,

-oli

**Comment by puethe** [comment]
Perfect, thanks!

**Pull request merged**
