### PR TITLE
Splitfastq bugfix

### PR DESCRIPTION
**Pull request by Oliver-Lorenz-dev**
workaround to stop the code splitting larger fastq files since it has problems with splitting such files.

### CODE REVIEW

**Comment by puethe** [comment]
Hi Oliver, I would suggest to do this differently, in order to avoid having hard-coded numbers in too many parts of the code. The chunk size is defined in (e.g.) https://github.com/sanger-pathogens/vr-codebase/blob/master/lib/VertRes/Utils/Mappers/smalt.pm, line 128. So I'd rather modify it there (and in sibling files).

**Comment by Oliver-Lorenz-dev** [comment]
> Hi Oliver, I would suggest to do this differently, in order to avoid having hard-coded numbers in too many parts of the code. The chunk size is defined in (e.g.) https://github.com/sanger-pathogens/vr-codebase/blob/master/lib/VertRes/Utils/Mappers/smalt.pm, line 128. So I'd rather modify it there (and in sibling files).

Hi Christoph, I'm not actually changing the chunk size variable here though. My idea was to put that if statement in which checked the total bases in the fastq so that the split functionality was kept for the smaller fastqs and then only removed for the very large fastqs, so it wouldn't reduce the efficiency of the pipeline very much. If I do what you suggest then I would have to bump up the chunk size to a massive number to remove the split functionality entirely (I think?). I get your point about the hard coded values, so happy to just bump up the chunk size if you prefer that.

**Comment by puethe** [comment]
Given that the number in smalt.pm is already larger than your number I'd expect no splitting to happen no matter what. I think the current logic is as follows:

- less than 1 billion bases: splits = 1 because of the chunk size
- more than 1 billion bases: splits = 1 because of your edit

Am I missing something?

**Comment by Oliver-Lorenz-dev** [comment]
> Given that the number in smalt.pm is already larger than your number I'd expect no splitting to happen no matter what. I think the current logic is as follows:
> 
> * less than 1 billion bases: splits = 1 because of the chunk size
> * more than 1 billion bases: splits = 1 because of your edit
> 
> Am I missing something?

No you're right, I wasn't aware of that part of the code overriding the default value for chunk size. So I guess we can just bump up the chunk size as you suggested to stop the splitting of very large files

**Comment by puethe** [comment]
Okay let's try that then.

**Review by puethe — APPROVED** [review]

**Pull request merged**
